# globals
backend-servers = ["localhost:2883"]
user = "guest"
pass = "guest"

[http]
listen-address = ":9000"

[mqtt-store]
connection-string = "root:@tcp(127.0.0.1:3306)/ninja"
mqtt-select = "select l.uid, l.mqtt_id from legends l where l.mqtt_id = ?"

[ws-store]
connection-string = "root:@tcp(127.0.0.1:3306)/ninja"
mqtt-select = "select l.uid, l.mqtt_id from legends l where l.mqtt_id = ?"

[mqtt]
listen-address = ":8883"
cert = "ssl/cert.pem"
key = "ssl/key.pem"
